[package]
name = "aoc-in-a-second"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "days"
harness = false